version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: h@rd2h@ck
    volumes:
      - ./.data:/var/lib/mysql
      - ./data/init.sql:/data/application/init.sql
    ports:
      - "3307:3306"
    networks:
      - mysql

networks:
  mysql:
    driver: bridge